// THIS FILE IS AUTOGENERATED, DO NOT EDIT

#ifndef GENERATED_OPENAPI_CODEGEN_API_H
#define GENERATED_OPENAPI_CODEGEN_API_H

#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#include "fiobj.h"

typedef enum api_gen_value_enum_e {
  ONEOF_VALUE_STRING,
  ONEOF_VALUE_NUMBER,
  ONEOF_VALUE_BOOLEAN,
  ONEOF_VALUE_NULL,
} api_gen_value_enum_t;

typedef union api_gen_value_union_u {
  const char* oneof_string;
  int64_t oneof_number;
  bool oneof_boolean;
  void* oneof_null;
} api_gen_value_union_t;

typedef struct api_gen_value_s {
  api_gen_value_enum_t discriminator;
  api_gen_value_union_t value;
} api_gen_value_t;

typedef struct api_gen_row_s {
  api_gen_value_t* buffer;
  size_t size;
} api_gen_row_t;

typedef struct api_gen_row_set_s {
  api_gen_row_t* buffer;
  size_t size;
} api_gen_row_set_t;

typedef struct api_gen_db_response_s {
  api_gen_row_set_t data;
} api_gen_db_response_t;

////////////////////////////////////////////////////////////////////////////////
//// Helper functions
////////////////////////////////////////////////////////////////////////////////

api_gen_value_t api_gen_value_parse_from_fiobj(FIOBJ);

typedef enum api_gen_value_enum_e {
  ONEOF_VALUE_STRING,
  ONEOF_VALUE_NUMBER,
  ONEOF_VALUE_BOOLEAN,
  ONEOF_VALUE_NULL,
} api_gen_value_enum_t;

typedef union api_gen_value_union_u {
  const char* oneof_string;
  int64_t oneof_number;
  bool oneof_boolean;
  void* oneof_null;
} api_gen_value_union_t;

typedef struct api_gen_value_s {
  api_gen_value_enum_t discriminator;
  api_gen_value_union_t value;
} api_gen_value_t;

FIOBJ api_gen_value_serialize_to_fiobj(api_gen_value_t);

void api_gen_value_cleanup(api_gen_value_t);

api_gen_row_t api_gen_row_parse_from_fiobj(FIOBJ);

typedef struct api_gen_row_s {
  api_gen_value_t* buffer;
  size_t size;
} api_gen_row_t;

FIOBJ api_gen_row_serialize_to_fiobj(api_gen_row_t);

void api_gen_row_cleanup(api_gen_row_t);

api_gen_row_set_t api_gen_row_set_parse_from_fiobj(FIOBJ);

typedef struct api_gen_row_set_s {
  api_gen_row_t* buffer;
  size_t size;
} api_gen_row_set_t;

FIOBJ api_gen_row_set_serialize_to_fiobj(api_gen_row_set_t);

void api_gen_row_set_cleanup(api_gen_row_set_t);

api_gen_db_response_t api_gen_db_response_parse_from_fiobj(FIOBJ);

FIOBJ api_gen_db_response_serialize_to_fiobj(api_gen_db_response_t);

void api_gen_db_response_cleanup(api_gen_db_response_t);

#endif // #ifndef GENERATED_OPENAPI_CODEGEN_API_H
