// THIS FILE IS AUTOGENERATED, DO NOT EDIT

#ifndef GENERATED_OPENAPI_CODEGEN_API_H
#define GENERATED_OPENAPI_CODEGEN_API_H

#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#include "fiobj.h"

typedef struct api_gen_meal_s {
  const char* mealName;
  const char* mealDescription;
  const char* mealPictureUrl;
} api_gen_meal_t;

typedef struct api_gen_meals_list_s {
  api_gen_meal_t* buffer;
  size_t size;
} api_gen_meals_list_t;

typedef struct api_gen_menu_s {
  api_gen_meals_list_t meals;
} api_gen_menu_t;

typedef struct api_gen_business_s {
  const char* businessId;
  const char* businessName;
  const char* ownerUserId;
  const char* description;
  const char* businessLogoUrl;
} api_gen_business_t;

typedef struct api_gen_v1_add_meal_to_menu_response_s {
  api_gen_menu_t menu;
} api_gen_v1_add_meal_to_menu_response_t;

typedef struct api_gen_v1_add_meal_to_menu_request_s {
  api_gen_meal_t meal;
} api_gen_v1_add_meal_to_menu_request_t;

typedef struct api_gen_v1_get_business_response_s {
  api_gen_business_t business;
} api_gen_v1_get_business_response_t;

typedef struct api_gen_v1_get_business_request_s {
  const char* businessId;
} api_gen_v1_get_business_request_t;

typedef struct api_gen_v1_delete_business_request_s {
  const char* businessId;
} api_gen_v1_delete_business_request_t;

typedef struct api_gen_v1_update_business_request_s {
  const char* businessId;
  const char* businessName;
  const char* ownerUserId;
  const char* description;
  const char* businessLogoUrl;
} api_gen_v1_update_business_request_t;

typedef struct api_gen_v1_create_business_response_s {
  const char* business_id;
} api_gen_v1_create_business_response_t;

typedef struct api_gen_v1_create_business_request_s {
  const char* businessName;
  const char* ownerUserId;
  const char* description;
  const char* businessLogoUrl;
} api_gen_v1_create_business_request_t;

FIOBJ api_gen_meal_serialize_to_fiobj(api_gen_meal_t);

FIOBJ api_gen_meals_list_serialize_to_fiobj(api_gen_meals_list_t);

FIOBJ api_gen_menu_serialize_to_fiobj(api_gen_menu_t);

FIOBJ api_gen_business_serialize_to_fiobj(api_gen_business_t);

FIOBJ api_gen_v1_add_meal_to_menu_response_serialize_to_fiobj(api_gen_v1_add_meal_to_menu_response_t);

FIOBJ api_gen_v1_add_meal_to_menu_request_serialize_to_fiobj(api_gen_v1_add_meal_to_menu_request_t);

FIOBJ api_gen_v1_get_business_response_serialize_to_fiobj(api_gen_v1_get_business_response_t);

FIOBJ api_gen_v1_get_business_request_serialize_to_fiobj(api_gen_v1_get_business_request_t);

FIOBJ api_gen_v1_delete_business_request_serialize_to_fiobj(api_gen_v1_delete_business_request_t);

FIOBJ api_gen_v1_update_business_request_serialize_to_fiobj(api_gen_v1_update_business_request_t);

FIOBJ api_gen_v1_create_business_response_serialize_to_fiobj(api_gen_v1_create_business_response_t);

FIOBJ api_gen_v1_create_business_request_serialize_to_fiobj(api_gen_v1_create_business_request_t);

api_gen_meal_t api_gen_meal_parse_from_fiobj(FIOBJ);

api_gen_meals_list_t api_gen_meals_list_parse_from_fiobj(FIOBJ);

api_gen_menu_t api_gen_menu_parse_from_fiobj(FIOBJ);

api_gen_business_t api_gen_business_parse_from_fiobj(FIOBJ);

api_gen_v1_add_meal_to_menu_response_t api_gen_v1_add_meal_to_menu_response_parse_from_fiobj(FIOBJ);

api_gen_v1_add_meal_to_menu_request_t api_gen_v1_add_meal_to_menu_request_parse_from_fiobj(FIOBJ);

api_gen_v1_get_business_response_t api_gen_v1_get_business_response_parse_from_fiobj(FIOBJ);

api_gen_v1_get_business_request_t api_gen_v1_get_business_request_parse_from_fiobj(FIOBJ);

api_gen_v1_delete_business_request_t api_gen_v1_delete_business_request_parse_from_fiobj(FIOBJ);

api_gen_v1_update_business_request_t api_gen_v1_update_business_request_parse_from_fiobj(FIOBJ);

api_gen_v1_create_business_response_t api_gen_v1_create_business_response_parse_from_fiobj(FIOBJ);

api_gen_v1_create_business_request_t api_gen_v1_create_business_request_parse_from_fiobj(FIOBJ);

void api_gen_meal_cleanup(api_gen_meal_t);

void api_gen_meals_list_cleanup(api_gen_meals_list_t);

void api_gen_menu_cleanup(api_gen_menu_t);

void api_gen_business_cleanup(api_gen_business_t);

void api_gen_v1_add_meal_to_menu_response_cleanup(api_gen_v1_add_meal_to_menu_response_t);

void api_gen_v1_add_meal_to_menu_request_cleanup(api_gen_v1_add_meal_to_menu_request_t);

void api_gen_v1_get_business_response_cleanup(api_gen_v1_get_business_response_t);

void api_gen_v1_get_business_request_cleanup(api_gen_v1_get_business_request_t);

void api_gen_v1_delete_business_request_cleanup(api_gen_v1_delete_business_request_t);

void api_gen_v1_update_business_request_cleanup(api_gen_v1_update_business_request_t);

void api_gen_v1_create_business_response_cleanup(api_gen_v1_create_business_response_t);

void api_gen_v1_create_business_request_cleanup(api_gen_v1_create_business_request_t);

#endif // #ifndef GENERATED_OPENAPI_CODEGEN_API_H
