spring:
  application:
    name: order
  datasource:
    url: jdbc:postgresql://localhost:5432/jetmeal_order
    username: jetmeal
    password: jetmeal
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    clear-checksums: true
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092

order:
  kafka:
    topic: order.changed
  clients:
    business-service-url: http://localhost:9000

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
