apiVersion: v1
kind: Service
metadata:
  name: shdb-service
  namespace: jet-meal
spec:
  selector:
    app: shdb-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
