version: '3.8'

services:
  shdb:
    container_name: shdb-sample
    build: .
    restart: unless-stopped
    environment:
      - SHDB_FRAMES=1000
    ports:
      - "8080:8080"
    volumes:
      - shdb-data:/var/lib/shdb/data

volumes:
  shdb-data:
