openapi: 3.1.0
info:
  title: Delivery Service
  description: Delivery service
  version: 1.0.0
paths:
  /couriers/register:
    post:
      tags:
        - couriers
      operationId: register_courier
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CourierCreateRequest'
      responses:
        '201':
          description: Courier registered
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Courier'
    put:
      tags:
        - couriers
      operationId: update_courier
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CourierCreateRequest'
      responses:
        '200':
          description: Courier updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Courier'

  /couriers/{id}:
    get:
      tags:
        - couriers
      operationId: get_courier_by_id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Courier found successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Courier'

  /couriers/{id}/update-position:
    post:
      tags:
        - couriers
      operationId: update_courier_position
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Point'
      responses:
        '200':
          description: Updated courier position

  /order/{id}/get-courier-position:
    get:
      tags:
        - orders
      operationId: get_courier_for_order
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Courier position fetched for the order
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CourierPositionInfo'

  /geo/distance:
    post:
      tags:
        - geo
      operationId: calculate_distance
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DistanceCalculateRequest'
      responses:
        '201':
          description: Calculated distance
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DistanceEstimationData'

  /geo/route:
    post:
      tags:
        - geo
      operationId: calculate_route
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RouteCalculateRequest'
      responses:
        '200':
          description: Route to destination

components:
  schemas:
    Courier:
      type: object
      required:
        - id
        - user_id
      properties:
        id:
          type: string
          format: uuid
        user_id:
          type: string
          format: uuid

    Point:
      type: object
      required:
        - lat
        - lon
      properties:
        lat:
          type: number
          format: double
        lon:
          type: number
          format: double

    Address:
      type: object
      required:
        - country
        - city
        - street
        - house
      properties:
        country:
          type: string
        city:
          type: string
        street:
          type: string
        house:
          type: string
        apartment:
          type: string
        instructions:
          type: string
        location:
          $ref: '#/components/schemas/Point'

    Location:
      type: object
      properties:
        location:
          $ref: '#/components/schemas/Point'
        address:
          $ref: '#/components/schemas/Address'
      anyOf:
        - required: [location]
        - required: [address]

    CourierCreateRequest:
      type: object
      required:
        - user_id
      properties:
        user_id:
          type: string
          format: uuid

    RouteCalculateRequest:
      type: object
      required:
        - origin
        - destination
      properties:
        origin:
          $ref: '#/components/schemas/Location'
        destination:
          $ref: '#/components/schemas/Location'

    DistanceCalculateRequest:
      type: object
      required:
        - origin
        - destination
      properties:
        origin:
          $ref: '#/components/schemas/Location'
        destination:
          $ref: '#/components/schemas/Location'

    CourierPositionInfo:
      type: object
      required:
        - position
      properties:
        position:
          $ref: '#/components/schemas/Point'
        time_remaining_minutes:
          type: number
          format: int

    DistanceEstimationData:
      type: object
      required:
        - estimated_time_minutes
      properties:
        estimated_time_minutes:
          type: number
          format: int

    Route:
      type: object
      required:
        - path
      properties:
        path:
          type: array
          items:
            $ref: '#/components/schemas/Point'