apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  namespace: jet-meal
data:
  database.url: "postgresql://user:password@user-postgres-db.jet-meal.svc.cluster.local:5432/user_service_db"
  server.port: "8080"
