apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: jet-meal-frontend
spec:
  selector:
    istio: ingressgateway  # стандартный лейбл Istio IngressGateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - jet-meal.ru
    # Раскомментировать при наличии TLS:
    # - port:
    #     number: 443
    #     name: https
    #     protocol: HTTPS
    #   tls:
    #     mode: SIMPLE
    #     credentialName: jet-meal-tls
    #   hosts:
    #     - jet-meal.ru
