apiVersion: v1
kind: ConfigMap
metadata:
  name: billing-config
  namespace: jet-meal
data:
  postgres.dsn: "host=postgres port=5432 dbname=billing user=billing password=billing"
  billing.port: "8080"
