apiVersion: v1
kind: ConfigMap
metadata:
  name: billing-config
  namespace: jet-meal
data:
  postgres.dsn: "host=billing-postgres-db.jet-meal.svc.cluster.local port=5432 dbname=billing user=billing password=billing"
  billing.port: "8080"
