import os

import codegen_item_struct
import type_utils

import codegen_item_struct
import codegen_item_serialize
import codegen_item_parse
import codegen_item_cleanup


class OpenAPIToCGenerator:
    def __init__(self, spec, name):
        self.spec = spec
        self.schemas = self._extract_schemas()
        self.generated_type_utils = set()
        self.header_content = []
        self.source_content = []
        self.name = name
        self.codegen_items = [
            codegen_item_struct.StructCodegenItem(self),
            codegen_item_serialize.SerializeCodegenItem(self),
            codegen_item_parse.ParseCodegenItem(self),
            codegen_item_cleanup.CleanupCodegenItem(self),
        ]

    def _extract_schemas(self):
        if "components" in self.spec and "schemas" in self.spec["components"]:
            return self.spec["components"]["schemas"]
        return self.spec["definitions"]

    def _insert_primitives(self):
        path = os.path.dirname(os.path.abspath(__file__)) + "/primitives.c"
        primitives = open(path, "r").readlines()
        self.source_content += primitives

    def generate_all(self):
        self.header_content = [
            "// THIS FILE IS AUTOGENERATED, DO NOT EDIT\n\n"
            f"#ifndef GENERATED_OPENAPI_{self.name.upper()}_H\n",
            f"#define GENERATED_OPENAPI_{self.name.upper()}_H\n\n",
            "#include <stdbool.h>\n",
            "#include <stdint.h>\n",
            "#include <stdlib.h>\n",
            "#include <string.h>\n\n",
            "#include \"fiobj.h\"\n\n",
        ]

        self.source_content = [
            "// THIS FILE IS AUTOGENERATED, DO NOT EDIT\n\n"
            f"#include \"{self.name}.h\"\n\n",
        ]

        self._insert_primitives()
    
        for codegen_item in self.codegen_items:
            for name, schema in reversed(self.schemas.items()):
                codegen_item.generate(name, schema)

        self.header_content.append(f"#endif // #ifndef GENERATED_OPENAPI_{self.name.upper()}_H\n")

    def write_files(self, output_prefix):
        """Write header and source files."""
        header_file = f"{output_prefix}.h"
        source_file = f"{output_prefix}.c"

        with open(header_file, "w") as f:
            f.writelines(self.header_content)

        with open(source_file, "w") as f:
            f.writelines(self.source_content)


