apiVersion: v1
kind: Service
metadata:
  name: {{ include "ssr.name" . }}
  labels:
    {{- include "ssr.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "ssr.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
