spring.application.name=delivery

delivery.kafka.order-events-topic=order-events
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

spring.datasource.url=${DELIVERY_DB_URL:jdbc:postgresql://localhost:5432/delivery}
spring.datasource.username=${DELIVERY_DB_USERNAME:delivery}
spring.datasource.password=${DELIVERY_DB_PASSWORD:delivery}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.flyway.enabled=true

spring.kafka.consumer.group-id=${DELIVERY_KAFKA_GROUP_ID:delivery-service}
