apiVersion: v1
kind: ConfigMap
metadata:
  name: order-config
  namespace: jet-meal
data:
  spring.datasource.url: "jdbc:postgresql://order-postgres-db.jet-meal.svc.cluster.local:5432/jetmeal_order"
  spring.datasource.username: "jetmeal"
  spring.datasource.password: "TODO_secrets"
  spring.data.redis.host: "redis"
  spring.data.redis.port: "6379"
  spring.kafka.bootstrap-servers: "kafka.kafka.svc.cluster.local:9092"
  order.kafka.topic: "order.changed"
  order.clients.business-service-url: "http://businesses-service"
