apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: order-postgres-pvc
  namespace: jet-meal
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 0.5Gi

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: order-postgres-db
  namespace: jet-meal
spec:
  serviceName: order-postgres-db
  replicas: 1
  selector:
    matchLabels:
      app: order-postgres-db
  template:
    metadata:
      labels:
        app: order-postgres-db
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: jetmeal_order
            - name: POSTGRES_USER
              value: jetmeal
            - name: POSTGRES_PASSWORD
              value: TODO_secrets
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: order-postgres-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: order-postgres-db
  namespace: jet-meal
spec:
  selector:
    app: order-postgres-db
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None
